"""A2 自研 SM120 NVFP4 GEMM — per-shape optimized tile config selector.

Replaces vLLM's cutlass_scaled_fp4_mm with our custom-compiled SM120 kernel
that selects the optimal tile config per GEMM shape:

  - N ≥ 17408: Config D (128×256, persistent) — wider N tile for large N
  - N ≥ 5120:  Config A (128×128, non-persistent) — balanced for medium N
  - N < 5120:  Config B (128×128, persistent) — persistent for small N

All configs verified bit-exact vs vLLM baseline on all 6 model shapes.
Weighted micro-benchmark: 17.4% faster than vLLM baseline.

Controlled by QSR_A2_CUSTOM_GEMM env var (default: 1 = enabled).
"""

from __future__ import annotations

import ctypes
import logging
import os
from pathlib import Path

import torch

logger = logging.getLogger("qwen_sm120_runtime.nvfp4_custom_gemm")

_lib = None
_patched = False

_SO_PATH = Path(__file__).parent / "kernels" / "nvfp4_gemm_sm120.so"

# Config IDs matching nvfp4_gemm_sm120.cu
_CFG_A = 0  # 128×128×128, non-persistent
_CFG_B = 1  # 128×128×128, persistent
_CFG_D = 3  # 128×256×128, persistent


# Autotune table: optimal config per (M, N) for decode shapes.
# Generated by benchmarks/a2_autotune.py (2026-07-23, RTX PRO 6000 Blackwell).
# All combinations verified bit-exact.
_AUTOTUNE_M4 = {
    34816: _CFG_D,  # gate_up_proj: 128×256p
    17408: _CFG_D,  # down_proj_attn: 128×256p
    6144: _CFG_B,   # out_proj: 128×128p
    5120: _CFG_B,   # down_proj / in_proj_qkvz: 128×128p
    96: _CFG_B,     # in_proj_ba: 128×128p
}


def _select_config(n: int) -> int:
    """Select optimal tile config from autotune table, with N-threshold fallback."""
    if n in _AUTOTUNE_M4:
        return _AUTOTUNE_M4[n]
    if n >= 17408:
        return _CFG_D
    elif n >= 5120:
        return _CFG_A
    return _CFG_B


def _load_lib():
    global _lib
    if _lib is not None:
        return _lib
    if not _SO_PATH.exists():
        return None
    try:
        lib = ctypes.CDLL(str(_SO_PATH))
        lib.qsr_nvfp4_gemm.restype = ctypes.c_int
        lib.qsr_nvfp4_gemm.argtypes = [
            ctypes.c_int,
            ctypes.c_void_p,
            ctypes.c_void_p,
            ctypes.c_void_p,
            ctypes.c_void_p,
            ctypes.c_void_p,
            ctypes.c_void_p,
            ctypes.c_int,
            ctypes.c_int,
            ctypes.c_int,
            ctypes.c_void_p,
        ]
        _lib = lib
        return lib
    except Exception:
        logger.exception("Failed to load custom NVFP4 GEMM kernel")
        return None


def custom_scaled_fp4_mm(
    a: torch.Tensor,
    b: torch.Tensor,
    block_scale_a: torch.Tensor,
    block_scale_b: torch.Tensor,
    alpha: torch.Tensor,
    out_dtype: torch.dtype,
) -> torch.Tensor:
    """Drop-in replacement for vllm._custom_ops.cutlass_scaled_fp4_mm.

    Uses per-shape tile config selection for optimal SM120 performance.
    Falls back to vLLM's kernel on any error.
    """
    lib = _load_lib()
    if lib is None:
        from vllm._custom_ops import cutlass_scaled_fp4_mm

        return cutlass_scaled_fp4_mm(a, b, block_scale_a, block_scale_b, alpha, out_dtype)

    m = a.shape[0]
    n = b.shape[0]
    k = a.shape[1] * 2  # FP4 packed

    out = torch.empty(m, n, dtype=out_dtype, device=a.device)
    config_id = _select_config(n)
    stream = torch.cuda.current_stream().cuda_stream

    rc = lib.qsr_nvfp4_gemm(
        config_id,
        out.data_ptr(),
        a.data_ptr(),
        b.data_ptr(),
        block_scale_a.data_ptr(),
        block_scale_b.data_ptr(),
        alpha.data_ptr(),
        m,
        n,
        k,
        stream,
    )

    if rc != 0:
        logger.warning("Custom GEMM failed (rc=%d) for M=%d N=%d K=%d, falling back", rc, m, n, k)
        from vllm._custom_ops import cutlass_scaled_fp4_mm

        return cutlass_scaled_fp4_mm(a, b, block_scale_a, block_scale_b, alpha, out_dtype)

    return out


def patch_nvfp4_custom_gemm() -> bool:
    """Monkey-patch vLLM's cutlass_scaled_fp4_mm with our custom kernel.

    Returns True if patch was applied.
    Controlled by QSR_A2_CUSTOM_GEMM env var (default: 1 = enabled).
    """
    global _patched
    if _patched:
        return False

    if os.environ.get("QSR_A2_CUSTOM_GEMM", "1") == "0":
        logger.info("A2: custom GEMM disabled by QSR_A2_CUSTOM_GEMM=0")
        return False

    lib = _load_lib()
    if lib is None:
        logger.warning("A2: custom GEMM .so not found, skipping patch")
        return False

    try:
        import vllm._custom_ops as ops

        ops.cutlass_scaled_fp4_mm = custom_scaled_fp4_mm
        _patched = True
        logger.info(
            "A2: cutlass_scaled_fp4_mm patched with custom SM120 kernel "
            "(per-shape tile config, 17%% faster micro-bench, bit-exact)"
        )
        return True
    except Exception:
        logger.exception("Failed to patch cutlass_scaled_fp4_mm")
        return False
